# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: graph_profile.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='graph_profile.proto',
  package='graph_profile',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x13graph_profile.proto\x12\rgraph_profile\"\xce\x03\n\x07Profile\x12(\n\x05nodes\x18\x01 \x03(\x0b\x32\x19.graph_profile.Profile.Op\x12/\n\x05graph\x18\x02 \x03(\x0b\x32 .graph_profile.Profile.Adjacents\x1a\xbd\x02\n\x02Op\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x14\n\x0c\x63omp_time_us\x18\x02 \x01(\r\x12\x11\n\tnum_bytes\x18\x03 \x01(\r\x12\x31\n\x07op_type\x18\x04 \x01(\x0e\x32 .graph_profile.Profile.Op.OpType\x12\x33\n\x08mem_type\x18\x05 \x01(\x0e\x32!.graph_profile.Profile.Op.MemType\x12\x14\n\x0coutput_bytes\x18\x06 \x01(\r\"H\n\x07MemType\x12\n\n\x06TENSOR\x10\x00\x12\x11\n\rWRITEVARIABLE\x10\x01\x12\x10\n\x0cREADVARIABLE\x10\x02\x12\x0c\n\x08\x43ONSTANT\x10\x03\"8\n\x06OpType\x12\x0b\n\x07\x43OMPUTE\x10\x00\x12\n\n\x06MEMORY\x10\x01\x12\x15\n\x11\x43ONTROLDEPENDENCY\x10\x02\x1a(\n\tAdjacents\x12\x0c\n\x04node\x18\x01 \x01(\t\x12\r\n\x05succs\x18\x02 \x03(\tb\x06proto3'
)



_PROFILE_OP_MEMTYPE = _descriptor.EnumDescriptor(
  name='MemType',
  full_name='graph_profile.Profile.Op.MemType',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='TENSOR', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='WRITEVARIABLE', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='READVARIABLE', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='CONSTANT', index=3, number=3,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=329,
  serialized_end=401,
)
_sym_db.RegisterEnumDescriptor(_PROFILE_OP_MEMTYPE)

_PROFILE_OP_OPTYPE = _descriptor.EnumDescriptor(
  name='OpType',
  full_name='graph_profile.Profile.Op.OpType',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='COMPUTE', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='MEMORY', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='CONTROLDEPENDENCY', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=403,
  serialized_end=459,
)
_sym_db.RegisterEnumDescriptor(_PROFILE_OP_OPTYPE)


_PROFILE_OP = _descriptor.Descriptor(
  name='Op',
  full_name='graph_profile.Profile.Op',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='graph_profile.Profile.Op.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='comp_time_us', full_name='graph_profile.Profile.Op.comp_time_us', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='num_bytes', full_name='graph_profile.Profile.Op.num_bytes', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='op_type', full_name='graph_profile.Profile.Op.op_type', index=3,
      number=4, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='mem_type', full_name='graph_profile.Profile.Op.mem_type', index=4,
      number=5, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='output_bytes', full_name='graph_profile.Profile.Op.output_bytes', index=5,
      number=6, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _PROFILE_OP_MEMTYPE,
    _PROFILE_OP_OPTYPE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=142,
  serialized_end=459,
)

_PROFILE_ADJACENTS = _descriptor.Descriptor(
  name='Adjacents',
  full_name='graph_profile.Profile.Adjacents',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='node', full_name='graph_profile.Profile.Adjacents.node', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='succs', full_name='graph_profile.Profile.Adjacents.succs', index=1,
      number=2, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=461,
  serialized_end=501,
)

_PROFILE = _descriptor.Descriptor(
  name='Profile',
  full_name='graph_profile.Profile',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='nodes', full_name='graph_profile.Profile.nodes', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='graph', full_name='graph_profile.Profile.graph', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_PROFILE_OP, _PROFILE_ADJACENTS, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=39,
  serialized_end=501,
)

_PROFILE_OP.fields_by_name['op_type'].enum_type = _PROFILE_OP_OPTYPE
_PROFILE_OP.fields_by_name['mem_type'].enum_type = _PROFILE_OP_MEMTYPE
_PROFILE_OP.containing_type = _PROFILE
_PROFILE_OP_MEMTYPE.containing_type = _PROFILE_OP
_PROFILE_OP_OPTYPE.containing_type = _PROFILE_OP
_PROFILE_ADJACENTS.containing_type = _PROFILE
_PROFILE.fields_by_name['nodes'].message_type = _PROFILE_OP
_PROFILE.fields_by_name['graph'].message_type = _PROFILE_ADJACENTS
DESCRIPTOR.message_types_by_name['Profile'] = _PROFILE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Profile = _reflection.GeneratedProtocolMessageType('Profile', (_message.Message,), {

  'Op' : _reflection.GeneratedProtocolMessageType('Op', (_message.Message,), {
    'DESCRIPTOR' : _PROFILE_OP,
    '__module__' : 'graph_profile_pb2'
    # @@protoc_insertion_point(class_scope:graph_profile.Profile.Op)
    })
  ,

  'Adjacents' : _reflection.GeneratedProtocolMessageType('Adjacents', (_message.Message,), {
    'DESCRIPTOR' : _PROFILE_ADJACENTS,
    '__module__' : 'graph_profile_pb2'
    # @@protoc_insertion_point(class_scope:graph_profile.Profile.Adjacents)
    })
  ,
  'DESCRIPTOR' : _PROFILE,
  '__module__' : 'graph_profile_pb2'
  # @@protoc_insertion_point(class_scope:graph_profile.Profile)
  })
_sym_db.RegisterMessage(Profile)
_sym_db.RegisterMessage(Profile.Op)
_sym_db.RegisterMessage(Profile.Adjacents)


# @@protoc_insertion_point(module_scope)
